### ISSUE TITLE
Spring Val Split

### ISSUE THREAD

**Issue by skief** [princeton-vl/SEA-RAFT#10]
Hi,
currently I'm trying to reproduce your results and for the evaluation of the Spring dataset I was wondering which data you used for the validation split since Spring only provides a train-test split. For me the `python evaluate.py --cfg config/eval/spring-M.json --model models/Tartan-C-T-TSKH-spring540x960-M.pth` from your `eval.sh` script fails with `ValueError: Spring val directory does not exist: datasets/spring/val`.

**Comment by MemorySlices** [comment]
We separate sequences 0045 and 0047 from the original training set (see sec 4.3) as the subval set.
