### ISSUE TITLE
FastCorr and Backbone Problems.

### ISSUE THREAD

**Issue by yuefanhao** [princeton-vl/SEA-RAFT#11]
Hi, I have two questions:
First, I noticed that corr.py has a FastCorr class, which seems to be a faster method for locally relevant queries, so how is this embedded in the network? Have you tried this method? 
Second, can FNet and Cnet share a weight? In addition, the input of CNet is the concat of two images, which is better than the input of only one image? I have noticed that other studies seem to share CNet and FNet, and only one image passes through CNet.
Hope you could answer my questions, thank you.

**Comment by MemorySlices** [comment]
We did not use FastCorr. Also, we did not use shared backbones as FNet and CNet are substantially different when we want the CNet to provide an initial prediction. This direct regression in CNet is crucial to the performance.
