### ISSUE TITLE
Some Questions About CorrBlock.

### ISSUE THREAD

**Issue by yuefanhao** [princeton-vl/SEA-RAFT#13]
I noticed that the calculation of CostVolume is different in RAFT-Stereo and SEA-RAFT. RAFT-Stereo seems to be more efficient, why is SEA-RAFT not used? Also, in most stereo flows, the CostVolume is calculated using the global shift and then dot multiply and average method, instead of matrix multiplication in the non-stereo flow method. Is this because the flow produced in stereo flow is mainly the global motion? Thank you very much.

**Comment by MemorySlices** [comment]
After rectification, the stereo-flow is 1D, which allows more efficient implementations. We did not investigate the efficient implementations of CostVolume in SEA-RAFT.
