### ISSUE TITLE
Design choice: corr volume downsampling

### ISSUE THREAD

**Issue by magehrig** [princeton-vl/SEA-RAFT#23]
Hi,

Thanks for the nice work!
I glanced over the code and saw that you perform correlation volume at multiple scales by actually downsampling fmap2

https://github.com/princeton-vl/SEA-RAFT/blob/f41d0a7ebff0e09def0f8ba9ebfd961686013b41/core/corr.py#L74-L79

Why don't you average pool as in the original RAFT implementation? Is there some speed/accuracy tradeoff here?

**Comment by MemorySlices** [comment]
Mathematically they are the same. I didn't test the trade-off, but there should not be a big difference in inference time - it's not the bottleneck.
