### ISSUE TITLE
which model is better to use

### ISSUE THREAD

**Issue by fengduduaaa** [princeton-vl/SEA-RAFT#4]
Hello, if you calculate the light flow on Vimeo90K data set, which model is better to use

**Comment by MemorySlices** [comment]
Usually, more datasets used in training means better performance. You can have quick tests based on the provided weights.

**Comment by fengduduaaa** [comment]
So I would like to ask which of the trained models uses the most training data sets?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "princeton-vl/SEA-RAFT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月4日(星期二) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [princeton-vl/SEA-RAFT] which model is better to use (Issue #4)





 
Usually, more datasets used in training means better performance. You can have quick tests based on the provided weights.
