### ISSUE TITLE
How to export ONNX?

### ISSUE THREAD

**Issue by newforrestgump001** [princeton-vl/SEA-RAFT#6]
Where can I the onnx model, have you exported it yet? Thank you a lot!

**Comment by MemorySlices** [comment]
SEA-RAFT does not rely on custom layers. We did not export it but I think the standard onnx exporter should be enough.

**Comment by Kololu777** [comment]
I thought converting SEA-RAFT to ONNX could be super useful for the community, 
so I wrote the conversion code! (https://github.com/Kololu777/onnx-sea-raft)
As pointed out, since SEA-RAFT mostly uses standard PyTorch features, it wasn’t too hard to pull off.

**Comment by MemorySlices** [comment]
Thank you for the code :D
