### ISSUE TITLE
Training Infrastructure

### ISSUE THREAD

**Issue by ChristophReich1996** [princeton-vl/SEA-RAFT#8]
Hi, great work! I'd like to know which compute infrastructure was used to train SEA-RAFT. More specifically, how many GPUs have been used to train SEA-RAFT, and how long did full training (w/ pre-training on TartanAir) take? Thanks for the help :)

**Comment by MemorySlices** [comment]
We trained SEA-RAFT on 8 L40s. I do not remember the full training time but I believe it can be done in <1 week. Specifically, the ablation setting (540 x 960 input, 12k steps) takes about <1.5 days for SEA-RAFT(M).

**Comment by ChristophReich1996** [comment]
Amazing, thanks for the details!

**Comment by emlcpfx** [comment]
What could be done to train the model further? Is the problem the availability of great datasets?

I find that any optical flow model has quite a bit of drift over time. Is that a lack of good real-world training data?

**Comment by emlcpfx** [comment]
Could one of the checkpoints be trained further on this dataset for better results?

https://github.com/google-research/kubric
