### ISSUE TITLE
SEA-RAFT L Checkpoints & Zero-Shot Validation

### ISSUE THREAD

**Issue by ChristophReich1996** [princeton-vl/SEA-RAFT#9]
Hi, great work again! Are the SEA-RAFT large checkpoints just the medium checkpoints with more refinement iterations? Additionally, I do not fully understand the zero-shot validation approach. In the paper, you are stating that you are downsampling the 1080p images of Kitti by a factor of two and upsample the optical flow again. However, the Kitti images have a resolution different than 1080p (typically 376  x 1241 pixels, but the size varies). Do you crop before downsampling, or do you use the original resolution (probably padded to accommodate the required backbone stride of 8)? Thanks again for the help :)

**Comment by MemorySlices** [comment]
SEA-RAFT(L) and SEA-RAFT(M) share the same weights. For Spring zero-shot evaluation, we use downsample-upsample strategy as mentioned in the papers. For KITTI and Sintel zero-shot eval, we use full-resolution images as the input without cropping.

**Comment by ChristophReich1996** [comment]
Thanks for the clarification; cheers, Christoph!
